### ISSUE TITLE
Download of the large hex file doesnt work. 

### ISSUE THREAD

**Issue by robertgregor** [Prosjekt2-09arduino/STK500-Android#53]
I am using the code on normal J2SE.
I have 2 files:
1st has around 17 kbytes. When I upload this file the arduino works well.
2nd has around 35 kbytes. When I upload this file, I will get true from the method - success, however Arduino doesnt work. Any idea?
Also question about to use the programUsingOptiboot(true, 128). I have optiboot loader, and if I have true there, it fail with the error, that reading from the EEPROM is not supported by optiboot. Why the software is trying to read EEPROM then? I am using programUsingOptiboot(false, 128). Then it is working.

**Comment by robertgregor** [comment]
I think, that the problem is codepage. After more investigations, it seems, that if the sketch ( or program) is bigger than 16 K the arduino doesnt start. So My assumption is, that the codepage is not well managed.

**Comment by bjorfoss** [comment]
**General**
I think the largest file we programmed was the [Mario example](https://github.com/Prosjekt2-09arduino/ArduinoStore/blob/master/Arduino/ComputerSerial/Examples/Mario/Mario.ino) from our Arduino Store project, which was 36.3kb in hex format. Based on your second comment, I believe your ino file was 35kb alone, though - with the added libraries I suppose your hex file is quite a bit larger than ours.

The programusingOptiboot method returns true as long as there are no explicit errors from the Arduino and there aren't too many communication issues; our app doesn't actually check the integrity of the programming attempt. We intended to verify each written batch of bytes, but there was a problem while reading from the Arduino and we had a deadline to meet. If it returned true it typically worked out all right.

**Debugging**
Have you looked at the log when these failed programming attempts claimed to succeed for the large file? You could change the debug level to make it spew out each batch of code it attempts to write (together with a lot of other info, though - you might want to tweak the output or parse the log) - then compare that to your hex file. At least you can isolate whether our program sends the correct data for large files. I recall there was a problem with addressing memory sections past a certain range, but that particular issue was fixed.

**Explanation and possible fixes**
I can explain the EEPROM error. There's a mistake in [line 1555](https://github.com/Prosjekt2-09arduino/STK500-Android/blob/master/src/no/group09/stk500_v1/STK500v1.java#L1555) that causes it to try to verify the written bytes in EEPROM instead of flash (it should be 'true' instead of 'false', or better yet, use a (probably existing) boolean specifying the type of memory it should read from). The STK500 protocol allows for read/write of EEPROM during programming, but as the bootloader doesn't support it, we simply throw an exception (full STK500 support was planned initially, but we only implemented the subset used by Optiboot).

Simply correcting that won't be enough, I noticed that the [writeAndReadFile method](https://github.com/Prosjekt2-09arduino/STK500-Android/blob/master/src/no/group09/stk500_v1/STK500v1.java#L1451-L1466) won't complain if the second invocation of uploadFile fails. Consequently, it wouldn't report it if the read found that the write had failed.

I can't test those fixes myself, as I no longer have access to an Arduino. If they make the verification work, however, it would at least retry programming if a silent write error occurred (if it turns out to be a communication issue).

**Comment by robertgregor** [comment]
Hello, OK, great, I didn't expect, that someone will even answer :+1:
I didn't fully get, what you wrote, however, I have changed line1555 to if(readPage(bytesToLoad, true) == tempArray) {
Then execute stk.programUsingOptiboot(true, 128). Ok, it looks like now, that it is going to 50 % and then its going again and again and again in endless loop. I looked to the log but I am not able to find there anything wrong.
![logcat txt](https://cloud.githubusercontent.com/assets/6962588/4603370/a2a1fb9a-5166-11e4-95ec-63b8f0853ac6.png)

**Comment by robertgregor** [comment]
BTW, that attached image is the logfile. Just rightclick and save as, then rename it to txt and you should see it :)

**Comment by bjorfoss** [comment]
Hi,

I tried replying to the notification email last night, but it doesn't seem to have been appended to the issue. By the way, I didn't expect my reply would get noticed either ;)

> Logcat 1413034753582 d: progress: 50 % 24706 / 24706
> Logcat 1413034753583 d: uploadFile: End of file. Upload finished with success.
> Logcat 1413034753583 d: progress: 50 %

The fraction indicates every line was written. The percentage is probably halved when verification of written bytes is enabled - I'll have to take a look at the progress estimation.

> Logcat 1413034753583 d: uploadFile: Data bytes to write: 128
> Logcat 1413034753583 d: Hex.getHexLine: startByte: 0, numberOfBytes: 128
> Logcat 1413034753583 v: uploadFile: 0, 128

Is that the end of the entire log file, or did it start repeating itself from there? It cuts off at a strange place, so I'd expect the latter. In that case, it would be nice to have a few more lines to better understand what it's doing.
When you say endless loop, is the program going from 0 to 50% again and again, or does it just freeze?

Did you leave the [writeAndReadFile method](https://github.com/Prosjekt2-09arduino/STK500-Android/blob/master/src/no/group09/stk500_v1/STK500v1.java#L1451-L1466) unchanged? Based on my previous reply, the concrete code change I suggested wouldn't be enough to fix the verification.

Please quote the parts that you found hard to understand from my previous reply.

**Update**
I've been looking some more at the code. The code for verifying written bytes is considerably faulty. Sorting it out would most likely entail a significant number of test runs for you, as I still don't have hardware to test on.

**Comment by robertgregor** [comment]
Wow, sorry, you was fast to answer :). For me no problem to test whatever. So to answer your questions:
It is not the end of the entire logfile. Because the behaviour is, that it is runing again and again and again. So it starts to repeating from there. So the program is going from 0 to 50% again and again.
I have modified the method writeAndReadFile and changed taht line 1555.like you suggested:
if(readPage(bytesToLoad, true) == tempArray) {

Robert
